### ISSUE TITLE
Change from DealClient to DaoDealClient

### ISSUE THREAD

**Issue by trruckerfling** [filecoin-project/fevm-data-dao-kit#5]
https://github.com/filecoin-project/fevm-data-dao-kit/blob/54e770b34931610caf7ecf9111234f62ff269c6c/contracts/DaoDealClient.sol#L74

Devs facing issue `Error: cannot find artifact "DaoDealClient"`. Identified by @rk-rishikesh, will need to update contract line from `DealClient` to `DaoDealClient` to fix

**Comment by ZakAyesh** [comment]
Fixed with this PR: 

https://github.com/filecoin-project/fevm-data-dao-kit/pull/4
